import { IPerson } from "../../interfaces/interfaces";
import TestovDM from "../../img/TestovDM.jpg"
import TipovaYaS from "../../img/TipovaYaS.jpg"
import DemovTP from "../../img/DemovTP.jpg"
import SaitovaVP from "../../img/SaitovaVP.jpg"
import PrimerovMD from "../../img/PrimerovMD.jpg"
import MokovAT from "../../img/MokovAT.jpg"
import PortalovaIS from "../../img/PortalovaIS.jpg"
import NodovDA from "../../img/NodovDA.jpg"
import DokerovIP from "../../img/DokerovIP.jpg"
import BashinAL from "../../img/BashinAL.jpg"
import MongovaDB from "../../img/MongovaDB.jpg"
import PostgresovSB from "../../img/PostgresovSB.jpg"
import RabotnikovIP from "../../img/RabotnikovIP.jpg"
import WorkerovPS from "../../img/WorkerovPS.jpg"
import ProrabovIS from "../../img/ProrabovIS.jpg"
import SikvelovEZ from "../../img/SikvelovEZ.jpg"
import SekurovaML from "../../img/SekurovaML.png"
import KoderovIP from "../../img/KoderovIP.jpg"
import AssemblerovaVP from "../../img/AssemblerovaVP.jpg"
import BasicovAB from "../../img/BasicovAB.jpg"
import { dateNow } from "../../helpers/helpers";

export const initialPersons: IPerson[] = [
    {
        id: 0,
        tabnumber: "1608743",
        surname: "Тестов",
        name: "Андрей",
        patronymic: "Васильевич",
        login: "TestovAM",
        email: "TestovAM@demoneftegaz.ru",
        photo: `url(${TestovDM})`,
        jobTitle: "Разработчик",
        departament: "Отдел по разработке портальных решений",
        departament_chief: 16,
        phoneNumber: "+79064163208",
        role: ['admin', 'user'],
        PKZI_name: "DNG_P-TestovAM",
        PKZI_date: "2023-07-11",
        adress: "г.Демо, Продуктовый проспект, 40",
        description: "6 этаж, к.632",
        map: "",
        official: "",
        absense: "",
        absense_date_in: "",
        absense_date_out: "",        
    },
    {
        id: 1,
        tabnumber: "1608344",
        surname: "Типова",
        name: "Ява",
        patronymic: "Скриптовна",
        login: "TipovaYaS",
        email: "TipovaYaS@demoneftegaz.ru",
        photo: `url(${TipovaYaS})`,
        jobTitle: "Начальник управления",
        departament: "Управление информационых технологий",
        departament_chief: 16,
        phoneNumber: "(62)16-32, +79032164080",
        role: ['user'],
        PKZI_name: "DNG_P-TipovaYaS",
        PKZI_date: "2023-04-12",
        adress: "г.Демо, Продуктовый проспект, 40",
        description: "2 этаж, к.23",
        map: "",
        official: "",
        rating: 4,         
        absense: "",
        absense_date_in: "",
        absense_date_out: "",
    },
    {
        id: 2,
        tabnumber: "1603432",
        surname: "Демов",
        name: "Семён",
        patronymic: "Примерович",
        login: "DemovTP",
        email: "DemovTP@demoneftegaz.ru",
        photo: `url(${DemovTP})`,
        jobTitle: "Ведущий специалист",
        departament: "Транспортный отдел",
        departament_chief: 16,
        phoneNumber: "(62)08-07, +79064160802",
        role: ['user'],
        PKZI_name: "DNG_P-DemovTP",
        PKZI_date: "2023-01-30",
        adress: "г.Демо, Продуктовый проспект, 40",
        description: "3 этаж, к.323",
        map: "",
        official: "",
        absense: "больничный",
        absense_date_in: dateNow(0),
        absense_date_out: dateNow(7),
        substitute: 1,
    },
    {
        id: 3,
        tabnumber: "1603465",
        surname: "Сайтова",
        name: "Вероника",
        patronymic: "Порталовна",
        login: "SaitovaVP",
        email: "SaitovaVP@demoneftegaz.ru",
        photo: `url(${SaitovaVP})`,
        jobTitle: "Специалист",
        departament: "Отдел информационного обеспечения",
        departament_chief: 16,
        phoneNumber: "(62)98-01, +79016001640",
        role: ['user'],
        PKZI_name: "DNG_P-SaitovaVP",
        PKZI_date: "2022-12-30",
        adress: "г.Демо, Продуктовый проспект, 40",
        description: "1 этаж, к.11",
        map: "",
        official: "",
        absense: "",
        absense_date_in: "",
        absense_date_out: "",
    },
    {
        id: 4,
        tabnumber: "1602397",
        surname: "Примеров",
        name: "Иван",
        patronymic: "Демович",
        login: "PrimerovMD",
        email: "PrimerovMD@demoneftegaz.ru",
        photo: `url(${PrimerovMD})`,
        jobTitle: "Главный специалист",
        departament: "Отдел добычи нефти и газа",
        departament_chief: 16,
        phoneNumber: "(62)12-46, +79032080200",
        role: ['user'],
        PKZI_name: "DNG_P-PrimerovMD",
        PKZI_date: "2023-08-21",
        adress: "г.Демо, Продуктовый проспект, 40",
        description: "8 этаж, к.811",
        map: "",
        official: "",
        rating: 3, 
        absense: "",
        absense_date_in: "",
        absense_date_out: "",
    },
    {
        id: 5,
        tabnumber: "1603864",
        surname: "Моков",
        name: "Александр",
        patronymic: "Тестович",
        login: "MokovAT",
        email: "MokovAT@demoneftegaz.ru",
        photo: `url(${MokovAT})`,
        jobTitle: "Главный специалист",
        departament: "Отдел добычи нефти и газа",
        departament_chief: 16,
        phoneNumber: "(62)12-46, +79032080200",
        role: ['user'],
        PKZI_name: "DNG_P-MokovAT",
        PKZI_date: "2023-09-22",
        adress: "г.Демо, Продуктовый проспект, 40",
        description: "11 этаж, к.1112",
        map: "",
        official: "",
        absense: "",
        absense_date_in: "",
        absense_date_out: "",
    },
    {
        id: 6,
        tabnumber: "1603864",
        surname: "Порталова",
        name: "Ирина",
        patronymic: "Сайтовна",
        login: "PortalovaIS",
        email: "PortalovaIS@demoneftegaz.ru",
        photo: `url(${PortalovaIS})`,
        jobTitle: "Начальник отдела",
        departament: "Отдел документооборота",
        departament_chief: 16,
        phoneNumber: "(62)01-36, +79096020016",
        role: ['user'],
        PKZI_name: "DNG_P-PortalovaIS",
        PKZI_date: "2023-02-20",
        adress: "г.Демо, Продуктовый проспект, 40",
        description: "12 этаж, к.1202",
        map: "",
        official: "",
        absense: "",
        absense_date_in: "",
        absense_date_out: "",
    },
    {
        id: 7,
        tabnumber: "1603974",
        surname: "Нодов",
        name: "Денис",
        patronymic: "Админович",
        login: "NodovDA",
        email: "NodovDA@demoneftegaz.ru",
        photo: `url(${NodovDA})`,
        jobTitle: "Старший специалист",
        departament: "Отдел аналитики",
        departament_chief: 16,
        phoneNumber: "(62)78-43, +79008020064",
        role: ['user'],
        PKZI_name: "DNG_P-NodovDA",
        PKZI_date: "2023-03-03",
        adress: "г.Демо, Продуктовый проспект, 40",
        description: "7 этаж, к.706",
        map: "",
        official: "",
        rating: 3,         
        absense: "командировка",
        absense_date_in: dateNow(-2),
        absense_date_out: dateNow(3),
    },
    {
        id: 8,
        tabnumber: "1603974",
        surname: "Докеров",
        name: "Игорь",
        patronymic: "Питонович",
        login: "DokerovIP",
        email: "DokerovIP@demoneftegaz.ru",
        photo: `url(${DokerovIP})`,
        jobTitle: "Начальник отдела",
        departament: "Отдел аналитики",
        departament_chief: 16,
        phoneNumber: "(62)78-42, +79032020062",
        role: ['user'],
        PKZI_name: "DNG_P-DokerovIP",
        PKZI_date: "2023-03-08",
        adress: "г.Демо, Продуктовый проспект, 40",
        description: "7 этаж, к.708",
        map: "",
        official: "",
        absense: "",
        absense_date_in: "",
        absense_date_out: "",
    },
    {
        id: 9,
        tabnumber: "1603974",
        surname: "Башин",
        name: "Алексей",
        patronymic: "Линуксович",
        login: "BashinAL",
        email: "BashinAL@demoneftegaz.ru",
        photo: `url(${BashinAL})`,
        jobTitle: "Начальник сектора",
        departament: "Сектор АХО",
        departament_chief: 16,
        phoneNumber: "(62)48-32, +79036023247",
        role: ['user'],
        PKZI_name: "DNG_P-BashinAL",
        PKZI_date: "2023-04-08",
        adress: "г.Демо, Продуктовый проспект, 40",
        description: "7 этаж, к.709",
        map: "",
        official: "",
        absense: "",
        absense_date_in: "",
        absense_date_out: "",
    },
    {
        id: 10,
        tabnumber: "1602209",
        surname: "Монгова",
        name: "Дарья",
        patronymic: "Базовна",
        login: "MongovaDB",
        email: "MongovaDB@demoneftegaz.ru",
        photo: `url(${MongovaDB})`,
        jobTitle: "Специалист",
        departament: "Сектор АХО",
        departament_chief: 16,
        phoneNumber: "(62)48-33, +79036023248",
        role: ['user'],
        PKZI_name: "DNG_P-MongovaDB",
        PKZI_date: "2023-05-08",
        adress: "г.Демо, Продуктовый проспект, 40",
        description: "9 этаж, к.904",
        map: "",
        official: "",
        absense: "",
        absense_date_in: "",
        absense_date_out: "",
    },
    {
        id: 11,
        tabnumber: "1603987",
        surname: "Постгресов",
        name: "Семен",
        patronymic: "Базович",
        login: "PostgresovSB",
        email: "PostgresovSB@demoneftegaz.ru",
        photo: `url(${PostgresovSB})`,
        jobTitle: "Инженер 2 категории",
        departament: "Сектор бизнес-планирования",
        departament_chief: 16,
        phoneNumber: "(62)33-31, +79044085248",
        role: ['user'],
        PKZI_name: "DNG_P-PostgresovSB",
        PKZI_date: "2023-06-24",
        adress: "г.Демо, Продуктовый проспект, 40",
        description: "9 этаж, к.932",
        map: "",
        official: "",
        absense: "обучение",
        absense_date_in: dateNow(1),
        absense_date_out: dateNow(3),
    },
    {
        id: 12,
        tabnumber: "1600473",
        surname: "Отладчиков",
        name: "Федор",
        patronymic: "Дебажевич",
        login: "OtladchikovFD",
        email: "DNG-GMarksheider@demoneftegaz.ru",
        photo: "",
        jobTitle: "Инженер 1 категории",
        departament: "Отдел землепользования",
        departament_chief: 16,
        phoneNumber: "(62)32-22, +79062085238",
        role: ['user'],
        PKZI_name: "DNG_P-OtladchikovFD",
        PKZI_date: "2023-03-14",
        adress: "г.Демо, Продуктовый проспект, 40",
        description: "3 этаж, к.332",
        map: "",
        official: "ДНГ Главный маркшейдер",
        absense: "",
        absense_date_in: "",
        absense_date_out: "",
    },
    {
        id: 13,
        tabnumber: "1605678",
        surname: "Повершелова",
        name: "Ирина",
        patronymic: "Скриптовна",
        login: "PowershelovaIS",
        email: "DNG-Personal@demoneftegaz.ru",
        photo: "",
        jobTitle: "Инженер",
        departament: "Управление по работе с персоналом",
        departament_chief: 16,
        phoneNumber: "(62)12-12, +79023080000",
        role: ['user'],
        PKZI_name: "DNG_P-PowershelovaIS",
        PKZI_date: "2023-01-11",
        adress: "г.Демо, Продуктовый проспект, 40",
        description: "1 этаж, к.3",
        map: "",
        official: "ДНГ Приемная ЗГД по персоналу",
        absense: "",
        absense_date_in: "",
        absense_date_out: "",
    },
    {
        id: 14,
        tabnumber: "1602354",
        surname: "Перлов",
        name: "Василий",
        patronymic: "Пайтонович",
        login: "PerlovVP",
        email: "DNG-PBU@demoneftegaz.ru",
        photo: "",
        jobTitle: "Специалист",
        departament: "Планово-бюджетное управление",
        departament_chief: 16,
        phoneNumber: "(62)14-01, +79011080000",
        role: ['user'],
        PKZI_name: "DNG_P-PerlovVP",
        PKZI_date: "2023-08-12",
        adress: "г.Демо, Продуктовый проспект, 40",
        description: "3 этаж, к.37",
        map: "",
        official: "ДНГ Планово-бюджетное управление",
        absense: "",
        absense_date_in: "",
        absense_date_out: "",
    },
    {
        id: 15,
        tabnumber: "1609921",
        surname: "Джавова",
        name: "Яна",
        patronymic: "Лисповна",
        login: "JavovaJaL",
        email: "DNG-PBOTOS@demoneftegaz.ru",
        photo: "",
        jobTitle: "Специалист",
        departament: "Управление по охране труда",
        departament_chief: 16,
        phoneNumber: "(62)15-01, +79022080300",
        role: ['user'],
        PKZI_name: "DNG_P-JavovaJaL",
        PKZI_date: "2023-02-02",
        adress: "г.Демо, Продуктовый проспект, 40",
        description: "3 этаж, к.36",
        map: "",
        official: "ДНГ Управление по охране труда",
        absense: "",
        absense_date_in: "",
        absense_date_out: "",
    },
    {
        id: 16,
        tabnumber: "1600001",
        surname: "Хаскелев",
        name: "Семен",
        patronymic: "Игоревич",
        login: "HakelevSI",
        email: "DNG-Top@demoneftegaz.ru",
        photo: "",
        jobTitle: "Главный инженер",
        departament: "Руководство",
        departament_chief: 16,
        phoneNumber: "(62)20-01, +79022080301",
        role: ['user'],
        PKZI_name: "DNG_P-HakelevSI",
        PKZI_date: "2023-02-04",
        adress: "г.Демо, Продуктовый проспект, 40",
        description: "3 этаж, к.31",
        map: "",
        official: "ДНГ Руководство",
        absense: "",
        absense_date_in: "",
        absense_date_out: "",
    },
    {
        id: 17,
        tabnumber: "1600121",
        surname: "Прорабов",
        name: "Иван",
        patronymic: "Скалярович",
        login: "ProrabovIS",
        email: "ProrabovIS@demoneftegaz.ru",
        photo: `url(${ProrabovIS})`,
        jobTitle: "Начальник цеха",
        departament: "Цех 5",
        departament_chief: 16,
        phoneNumber: "(62)25-01, +79022065971",
        role: ['user'],
        PKZI_name: "DNG_P-ProrabovIS",
        PKZI_date: "2023-04-08",
        adress: "г.Демо, Складской переулок, 83",
        description: "1 этаж, к.14",
        map: "",
        official: "",
        absense: "",
        absense_date_in: "",
        absense_date_out: "",
    },
    {
        id: 18,
        tabnumber: "1600124",
        surname: "Воркеров",
        name: "Павел",
        patronymic: "Стаханович",
        login: "WorkerovPS",
        email: "WorkerovPS@demoneftegaz.ru",
        photo: `url(${WorkerovPS})`,
        jobTitle: "Мастер",
        departament: "Цех 5",
        departament_chief: 16,
        phoneNumber: "(62)44-01, +79063045961",
        role: ['user'],
        PKZI_name: "DNG_P-WorkerovPS",
        PKZI_date: "2023-03-18",
        adress: "г.Демо, Складской переулок, 83",
        description: "1 этаж, к.18",
        map: "",
        official: "",
        rating: 5,         
        absense: "",
        absense_date_in: "",
        absense_date_out: "",
    },
    {
        id: 19,
        tabnumber: "1600241",
        surname: "Работников",
        name: "Игорь",
        patronymic: "Павлович",
        login: "RabotnikovIP",
        email: "RabotnikovIP@demoneftegaz.ru",
        photo: `url(${RabotnikovIP})`,
        jobTitle: "Мастер",
        departament: "Цех 5",
        departament_chief: 16,
        phoneNumber: "(62)74-01, +79023047961",
        role: ['user'],
        PKZI_name: "DNG_P-RabotnikovIP",
        PKZI_date: "2023-03-17",
        adress: "г.Демо, Складской переулок, 83",
        description: "1 этаж, к.18",
        map: "",
        official: "",
        absense: "",
        absense_date_in: "",
        absense_date_out: "",
    },
    {
        id: 20,
        tabnumber: "1600003",
        surname: "Фряхин",
        name: "Борис",
        patronymic: "Инсталлерович",
        login: "FryachinBI",
        email: "DNG-IT@demoneftegaz.ru",
        photo: "",
        jobTitle: "Главный специалист",
        departament: "Управление информационых технологий",
        departament_chief: 1,
        phoneNumber: "(62)23-01, +79022484301",
        role: ['user'],
        PKZI_name: "DNG_P-FryachinBI",
        PKZI_date: "2023-02-03",
        adress: "г.Демо, Продуктовый проспект, 40",
        description: "3 этаж, к.34",
        map: "",
        official: "ДНГ Управление информационых технологий",
        absense: "",
        absense_date_in: "",
        absense_date_out: "",
    },
    {
        id: 21,
        tabnumber: "1600501",
        surname: "Юниксов",
        name: "Альберт",
        patronymic: "Перлович",
        login: "UnixovAP",
        email: "DNG-Analitics@demoneftegaz.ru",
        photo: "",
        jobTitle: "Ведущий специалист",
        departament: "Отдел аналитики",
        departament_chief: 8,
        phoneNumber: "(62)23-51, +79024484341",
        role: ['user'],
        PKZI_name: "DNG_P-UnixovAPBI",
        PKZI_date: "2023-03-01",
        adress: "г.Демо, Продуктовый проспект, 40",
        description: "3 этаж, к.46",
        map: "",
        official: "ДНГ Отдел аналитики",
        absense: "",
        absense_date_in: "",
        absense_date_out: "",
    },
    {
        id: 22,
        tabnumber: "1604501",
        surname: "Кубернетисова",
        name: "Алия",
        patronymic: "Гугловна",
        login: "KubertenisovaAG",
        email: "DNG-Documentooborot@demoneftegaz.ru",
        photo: "",
        jobTitle: "Старший специалист",
        departament: "Отдел документооборота",
        departament_chief: 6,
        phoneNumber: "(62)13-51, +79044484341",
        role: ['user'],
        PKZI_name: "DNG_P-KubertenisovaAG",
        PKZI_date: "2023-05-05",
        adress: "г.Демо, Продуктовый проспект, 40",
        description: "3 этаж, к.42",
        map: "",
        official: "ДНГ Отдел документооборота",
        absense: "",
        absense_date_in: "",
        absense_date_out: "",
    },
    {
        id: 23,
        tabnumber: "1600573",
        surname: "Сиквелов",
        name: "Егор",
        patronymic: "Запросович",
        login: "SikvelovEZ",
        email: "DNG-GMarksheider@demoneftegaz.ru",
        photo: `url(${SikvelovEZ})`,
        jobTitle: "Главный маркшейдер",
        departament: "Отдел землепользования",
        departament_chief: 16,
        phoneNumber: "(62)32-26, +79063085238",
        role: ['user'],
        PKZI_name: "DNG_P-SikvelovEZ",
        PKZI_date: "2023-01-14",
        adress: "г.Демо, Продуктовый проспект, 40",
        description: "1 этаж, к.132",
        map: "",
        official: "ДНГ Главный маркшейдер",
        absense: "",
        absense_date_in: "",
        absense_date_out: "",
    },
    {
        id: 24,
        tabnumber: "1609924",
        surname: "Секьюрова",
        name: "Марина",
        patronymic: "Львовна",
        login: "SekurovaML",
        email: "SekurovaML@demoneftegaz.ru",
        photo: `url(${SekurovaML})`,
        jobTitle: "Начальник управления",
        departament: "Управление по охране труда",
        departament_chief: 16,
        phoneNumber: "(62)17-41, +79023050300",
        role: ['user'],
        PKZI_name: "DNG_P-SekurovaML",
        PKZI_date: "2023-07-03",
        adress: "г.Демо, Продуктовый проспект, 40",
        description: "5 этаж, к.56",
        map: "",
        official: "",
        absense: "",
        absense_date_in: "",
        absense_date_out: "",
    },
    {
        id: 25,
        tabnumber: "1604578",
        surname: "Кодеров",
        name: "Иван",
        patronymic: "Паскалевич",
        login: "KoderovIP",
        email: "KoderovIP@demoneftegaz.ru",
        photo: `url(${KoderovIP})`,
        jobTitle: "Начальник управления",
        departament: "Управление по работе с персоналом",
        departament_chief: 16,
        phoneNumber: "(62)22-42, +79023080440",
        role: ['user'],
        PKZI_name: "DNG_P-KoderovIP",
        PKZI_date: "2023-06-16",
        adress: "г.Демо, Продуктовый проспект, 40",
        description: "7 этаж, к.71",
        map: "",
        official: "",
        absense: "",
        absense_date_in: "",
        absense_date_out: "",
    },
    {
        id: 26,
        tabnumber: "1602454",
        surname: "Ассемблерова",
        name: "Василиса",
        patronymic: "Байтовна",
        login: "AssemblerovaVP",
        email: "AssemblerovaVP@demoneftegaz.ru",
        photo: `url(${AssemblerovaVP})`,
        jobTitle: "Начальник управления",
        departament: "Планово-бюджетное управление",
        departament_chief: 16,
        phoneNumber: "(62)55-01, +790110550000",
        role: ['user'],
        PKZI_name: "DNG_P-AssemblerovaVP",
        PKZI_date: "2023-04-15",
        adress: "г.Демо, Продуктовый проспект, 40",
        description: "7 этаж, к.77",
        map: "",
        official: "",
        absense: "",
        absense_date_in: "",
        absense_date_out: "",
    },
    {
        id: 27,
        tabnumber: "1600351",
        surname: "Бейсиков",
        name: "Антон",
        patronymic: "Бекашевич",
        login: "BasicovAB",
        email: "DNG-Ceh5@demoneftegaz.ru",
        photo: `url(${BasicovAB})`,
        jobTitle: "Старший специалист",
        departament: "Цех 5",
        departament_chief: 16,
        phoneNumber: "(62)35-01, +79022365931",
        role: ['user'],
        PKZI_name: "DNG_P-BasicovAB",
        PKZI_date: "2023-03-18",
        adress: "г.Демо, Складской переулок, 83",
        description: "1 этаж, к.11",
        map: "",
        official: "ДНГ Цех 5",
        absense: "",
        absense_date_in: "",
        absense_date_out: "",
    },
]