import { ITransport } from "../../interfaces/interfaces";

export const initialTransport: ITransport[] = [
    {
        id: 0,
        number: "ДНГ/Т/1",
        create_date: "09.09.2022",
        create_time: "8:25",
        person: 4,
        personsCount: 2,
        owner: 4,
        from: "Атлоновый проспект, д.48",
        destination: "ул. Силина, д.6",
        date: "10.09.2022",
        time_in: "10:30",
        time_out: "13:30",
        justification: "Совещание по ПБОТОС",
        status: "Выполнена",
        need_agreement_chief: false,
        agreement_person: 16,
        agreement_date: "09.09.2022",
        agreement_time: "13:44",
        car: "Рено Логан е234",
        driver: "Алексей, +79534547412",
        description: "От проходной",
    },
    {
        id: 1,
        number: "ДНГ/Т/2",
        create_date: "10.09.2022",
        create_time: "10:25",
        person: 0,
        personsCount: 3,
        owner: 0,
        from: "Ул. Селероновая, д.16",
        destination: "пр-т Зайчикова, д.14",
        date: "11.09.2022",
        time_in: "13:30",
        time_out: "16:30",
        justification: "Совещание по ГОЧС",
        status: "Выполнена",
        need_agreement_chief: false,
        agreement_person: 16,
        agreement_date: "10.09.2022",
        agreement_time: "11:41",
        car: "Лада Малина к123",
        driver: "Семен, +79865324575",
        description: "От гаража",
    },
    {
        id: 2,
        number: "ДНГ/Т/3",
        create_date: "11.09.2022",
        create_time: "10:11",
        person: 0,
        personsCount: 1,
        owner: 0,
        from: "Проезд Феномова, д.321",
        destination: "Ул. Тигриная, д.44",
        date: "12.09.2022",
        time_in: "8:30",
        time_out: "11:30",
        justification: "Закупочный тендер",
        status: "На согласовании",
        need_agreement_chief: false,
        agreement_person: 16,
        agreement_date: "",
        agreement_time: "",
        car: "",
        driver: "",
        description: "",
    },
    {
        id: 3,
        number: "ДНГ/Т/4",
        create_date: "12.09.2022",
        create_time: "10:11",
        person: 2,
        personsCount: 1,
        owner: 3,
        from: "Аэропорт",
        destination: "Ул. Воробьева, д.1",
        date: "15.09.2022",
        time_in: "10:30",
        time_out: "11:30",
        justification: "Встреча и размещение рабочей группы УНГ",
        status: "У диспетчера",
        need_agreement_chief: false,
        agreement_person: 16,
        agreement_date: "12.09.2022",
        agreement_time: "14:20",
        car: "",
        driver: "",
        description: "",
    },
    {
        id: 4,
        number: "ДНГ/Т/5",
        create_date: "15.09.2022",
        create_time: "8:25",
        person: 0,
        personsCount: 2,
        owner: 0,
        from: "Атлоновый проспект, д.48",
        destination: "ул. Силина, д.6",
        date: "16.09.2022",
        time_in: "10:30",
        time_out: "13:30",
        justification: "Осмотр помещений",
        status: "Выполнена",
        need_agreement_chief: false,
        agreement_person: 16,
        agreement_date: "15.09.2022",
        agreement_time: "13:44",
        car: "Рено Логан е234",
        driver: "Алексей, +79534547412",
        description: "От проходной",
    },
    {
        id: 5,
        number: "ДНГ/Т/6",
        create_date: "16.09.2022",
        create_time: "10:25",
        person: 5,
        personsCount: 3,
        owner: 5,
        from: "Ул. Селероновая, д.16",
        destination: "пр-т Зайчикова, д.14",
        date: "17.09.2022",
        time_in: "13:30",
        time_out: "16:30",
        justification: "Проверка условий труда",
        status: "Выполнена",
        need_agreement_chief: false,
        agreement_person: 16,
        agreement_date: "16.09.2022",
        agreement_time: "11:41",
        car: "Лада Малина к123",
        driver: "Семен, +79865324575",
        description: "От гаража",
    },
    {
        id: 6,
        number: "ДНГ/Т/7",
        create_date: "17.09.2022",
        create_time: "10:11",
        person: 0,
        personsCount: 1,
        owner: 0,
        from: "Проезд Феномова, д.321",
        destination: "Ул. Тигриная, д.44",
        date: "18.09.2022",
        time_in: "8:30",
        time_out: "11:30",
        justification: "Перемещение оргтехники",
        status: "На согласовании",
        need_agreement_chief: false,
        agreement_person: 16,
        agreement_date: "",
        agreement_time: "",
        car: "",
        driver: "",
        description: "",
    },
    {
        id: 7,
        number: "ДНГ/Т/8",
        create_date: "18.09.2022",
        create_time: "10:11",
        person: 0,
        personsCount: 1,
        owner: 0,
        from: "Атлоновый проспект, д.48",
        destination: "Ул. Тигриная, д.44",
        date: "19.09.2022",
        time_in: "10:30",
        time_out: "11:30",
        justification: "Совещание с ИТ-интегратом",
        status: "У диспетчера",
        need_agreement_chief: false,
        agreement_person: 16,
        agreement_date: "18.09.2022",
        agreement_time: "14:20",
        car: "",
        driver: "",
        description: "",
    },        
]

