import { dateNow } from "../../helpers/helpers"
import { IWorkAbsenseWeekend } from "../../interfaces/interfaces"

export const initialWorkAbsense: IWorkAbsenseWeekend[] = [
    {
        id: 0,
        number: "ДНГ/О/1",
        create_date: dateNow(-7),
        create_time: "8:15",
        person: 4,
        justification: "Посещение врача",
        absense_date_in: dateNow(-7),
        absense_date_out: dateNow(-7),
        absense_time_in: "11:00",
        absense_time_out: "13:00",
        status: "Согласовано руководителем",
        owner: 4,
        agreement_person: 16,
        agreement_date: dateNow(-7),
        agreement_time: "9:44"
    },
    {
        id: 1,
        number: "ДНГ/О/2",
        create_date: dateNow(-6),
        create_time: "9:17",
        person: 6,
        justification: "Выезд на объект ПДНГ-4",
        absense_date_in: dateNow(-6),
        absense_date_out: dateNow(-6),
        absense_time_in: "13:00",
        absense_time_out: "17:00",
        status: "Согласовано руководителем",
        owner: 6,
        agreement_person: 16,
        agreement_date: dateNow(-6),
        agreement_time: "10:55"
    },
    {
        id: 2,
        number: "ДНГ/О/3",
        create_date: dateNow(-5),
        create_time: "9:22",
        person: 8,
        justification: "Участие в совещании в ДНГ-Охрана",
        absense_date_in: dateNow(-5),
        absense_date_out: dateNow(-5),
        absense_time_in: "13:00",
        absense_time_out: "15:00",
        status: "Согласовано руководителем",
        owner: 8,
        agreement_person: 16,
        agreement_date: dateNow(-5),
        agreement_time: "10:11"
    },
    {
        id: 3,
        number: "ДНГ/О/4",
        create_date: dateNow(-4),
        create_time: "8:55",
        person: 2,
        justification: "Посещение страховой компании",
        absense_date_in: dateNow(-4),
        absense_date_out: dateNow(-4),
        absense_time_in: "14:00",
        absense_time_out: "15:00",
        status: "Согласовано руководителем",
        owner: 2,
        agreement_person: 16,
        agreement_date: dateNow(-4),
        agreement_time: "10:11"
    },
    {
        id: 4,
        number: "ДНГ/О/5",
        create_date: dateNow(-3),
        create_time: "8:15",
        person: 0,
        justification: "Посещение врача",
        absense_date_in: dateNow(-3),
        absense_date_out: dateNow(-3),
        absense_time_in: "14:00",
        absense_time_out: "15:00",
        status: "Согласовано руководителем",
        owner: 0,
        agreement_person: 16,
        agreement_date: dateNow(-3),
        agreement_time: "9:44"
    },
    {
        id: 5,
        number: "ДНГ/О/6",
        create_date: dateNow(-2),
        create_time: "9:17",
        person: 9,
        justification: "Выезд на объект ПДНГ-4",
        absense_date_in: dateNow(-2),
        absense_date_out: dateNow(-2),
        absense_time_in: "13:00",
        absense_time_out: "17:00",
        status: "Согласовано руководителем",
        owner: 9,
        agreement_person: 16,
        agreement_date: dateNow(-2),
        agreement_time: "10:55"
    },
    {
        id: 6,
        number: "ДНГ/О/7",
        create_date: dateNow(-1),
        create_time: "9:22",
        person: 12,
        justification: "Участие в совещании в ДНГ-Охрана",
        absense_date_in: dateNow(-1),
        absense_date_out: dateNow(-1),
        absense_time_in: "13:00",
        absense_time_out: "15:00",
        status: "Согласовано руководителем",
        owner: 12,
        agreement_person: 16,
        agreement_date: dateNow(-1),
        agreement_time: "10:11"
    },
    {
        id: 7,
        number: "ДНГ/О/8",
        create_date: dateNow(0),
        create_time: "8:55",
        person: 0,
        justification: "Посещение офиса на Спектрумской",
        absense_date_in: dateNow(0),
        absense_date_out: dateNow(0),
        absense_time_in: "14:00",
        absense_time_out: "15:00",
        status: "На согласовании",
        owner: 0,
        agreement_person: 16,
        agreement_date: dateNow(0),
        agreement_time: "10:11"
    },
    {
        id: 8,
        number: "ДНГ/О/9",
        create_date: dateNow(1),
        create_time: "7:45",
        person: 7,
        justification: "Посещение спортивного мероприятия",
        absense_date_in: dateNow(1),
        absense_date_out: dateNow(1),
        absense_time_in: "14:00",
        absense_time_out: "17:00",
        status: "На согласовании",
        owner: 7,
        agreement_person: 0,
        agreement_date: "",
        agreement_time: ""
    },
]

