import { dateNow } from "../../helpers/helpers"
import { IWorkAbsenseWeekend } from "../../interfaces/interfaces"

export const initialWorkWeekend: IWorkAbsenseWeekend[] = [
    {
        id: 0,
        number: "ДНГ/В/1",
        create_date: dateNow(-7),
        create_time: "8:15",
        person: 4,
        justification: "Работа в выходной день",
        absense_date_in: dateNow(-6),
        absense_date_out: dateNow(-6),
        absense_time_in: "08:00",
        absense_time_out: "17:00",
        status: "Согласовано руководителем",
        owner: 4,
        agreement_person: 16,
        agreement_date: dateNow(-7),
        agreement_time: "9:44"
    },
    {
        id: 1,
        number: "ДНГ/В/2",
        create_date: dateNow(-6),
        create_time: "9:17",
        person: 6,
        justification: "Работа в выходной день",
        absense_date_in: dateNow(-5),
        absense_date_out: dateNow(-5),
        absense_time_in: "08:00",
        absense_time_out: "17:00",
        status: "Согласовано руководителем",
        owner: 6,
        agreement_person: 16,
        agreement_date: dateNow(-6),
        agreement_time: "10:55"
    },
    {
        id: 2,
        number: "ДНГ/В/3",
        create_date: dateNow(-5),
        create_time: "9:22",
        person: 8,
        justification: "Работа в выходной день",
        absense_date_in: dateNow(-4),
        absense_date_out: dateNow(-4),
        absense_time_in: "08:00",
        absense_time_out: "17:00",
        status: "Согласовано руководителем",
        owner: 8,
        agreement_person: 16,
        agreement_date: dateNow(-5),
        agreement_time: "10:11"
    },
    {
        id: 3,
        number: "ДНГ/В/4",
        create_date: dateNow(-4),
        create_time: "8:55",
        person: 2,
        justification: "Работа в выходной день",
        absense_date_in: dateNow(-3),
        absense_date_out: dateNow(-3),
        absense_time_in: "08:00",
        absense_time_out: "17:00",
        status: "Согласовано руководителем",
        owner: 2,
        agreement_person: 16,
        agreement_date: dateNow(-4),
        agreement_time: "10:11"
    },
    {
        id: 4,
        number: "ДНГ/В/5",
        create_date: dateNow(-3),
        create_time: "8:15",
        person: 0,
        justification: "Работа в выходной день",
        absense_date_in: dateNow(-2),
        absense_date_out: dateNow(-2),
        absense_time_in: "08:00",
        absense_time_out: "17:00",
        status: "Согласовано руководителем",
        owner: 0,
        agreement_person: 16,
        agreement_date: dateNow(-3),
        agreement_time: "9:44"
    },
    {
        id: 5,
        number: "ДНГ/В/6",
        create_date: dateNow(-2),
        create_time: "9:17",
        person: 9,
        justification: "Работа в выходной день",
        absense_date_in: dateNow(-1),
        absense_date_out: dateNow(-1),
        absense_time_in: "08:00",
        absense_time_out: "17:00",
        status: "Согласовано руководителем",
        owner: 9,
        agreement_person: 16,
        agreement_date: dateNow(-2),
        agreement_time: "10:55"
    },
    {
        id: 6,
        number: "ДНГ/В/7",
        create_date: dateNow(-1),
        create_time: "9:22",
        person: 12,
        justification: "Работа в выходной день",
        absense_date_in: dateNow(0),
        absense_date_out: dateNow(0),
        absense_time_in: "08:00",
        absense_time_out: "17:00",
        status: "Согласовано руководителем",
        owner: 12,
        agreement_person: 16,
        agreement_date: dateNow(-1),
        agreement_time: "10:11"
    },
    {
        id: 7,
        number: "ДНГ/В/8",
        create_date: dateNow(0),
        create_time: "8:55",
        person: 0,
        justification: "Работа в выходной день",
        absense_date_in: dateNow(1),
        absense_date_out: dateNow(1),
        absense_time_in: "08:00",
        absense_time_out: "17:00",
        status: "На согласовании",
        owner: 0,
        agreement_person: 16,
        agreement_date: "",
        agreement_time: ""
    },
    {
        id: 8,
        number: "ДНГ/В/9",
        create_date: dateNow(0),
        create_time: "9:35",
        person: 4,
        justification: "Работа в выходной день",
        absense_date_in: dateNow(2),
        absense_date_out: dateNow(2),
        absense_time_in: "08:00",
        absense_time_out: "17:00",
        status: "На согласовании",
        owner: 4,
        agreement_person: 0,
        agreement_date: "",
        agreement_time: ""
    },
]

